services:
  mysql:
    container_name: mysql
    image: mysql:8.4.4
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    entrypoint:
      - bash
      - -c
      - |
        chmod 777 /docker-entrypoint-initdb.d/*.sql
        docker-entrypoint.sh mysqld
volumes:
  mysql_data: