---
apiVersion: v1
kind: Service
metadata:
  name: sdjpa-intro
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sdjpa-intro

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdjpa-intro
  labels:
    app: sdjpa-intro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdjpa-intro
  template:
    metadata:
      labels:
        app: sdjpa-intro
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.37.0
          command: [ 'sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;' ]
      containers:
        - name: sdjpa-intro
          image: domboeckli/sdjpa-intro:@project.version@
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            #initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6